### ISSUE TITLE
Fix tests for `isAuth.spec.ts` and ` src/server.ts`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1010]
**Describe the bug**
We have been getting periodic errors where our GitHub action testing fails. Re-running the tests often causes the error to go away.

1. [This is an example of one such failed test run.](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4097595336/jobs/7066087060)
2. Click through and you will see the screen shot below.

_Other_
1. This has been fixed with https://github.com/PalisadoesFoundation/talawa-api/pull/1007 however we need to ensure that this test correctly verifies the existence of the required resources to reduce any future failure scenarios.
1. That PR made modifications to [src/server.ts](https://github.com/PalisadoesFoundation/talawa-api/pull/1007/files#diff-8a8ae07582c9d433ec8c2e5c4310ff8901e604f4965c5b90a49117ad46c47595) This may mean that the tests for that file need to be fixed too.

**To Reproduce**
1. Submit a PR
1. `tests/middleware/isAuth.spec.ts` will occasionally fail.

**Expected behavior**
Tests pass reliably and consitently

**Actual behavior**
See above

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/216835781-dd015b93-1a99-4b22-b830-5c267596679b.png)

**Additional details**
N/A

**Comment by anshgoyalevil** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
You already have 2 issues assigned. Please wait until your other issues are closed via a PR merge

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?

**Comment by palisadoes** [comment]
Please look at duplicate issue https://github.com/PalisadoesFoundation/talawa-api/issues/1025 for any further details

**Comment by KrutikaBhatt** [comment]
@palisadoes, yes I will take a look. Thank you so much

**Comment by ayushbhaimehta** [comment]
Hey if no one is working on this then I would love to work on this please tell from where should I begin.

**Comment by palisadoes** [comment]
@ayushbhaimehta This issue was assigned just yesterday. Please take a look at other unassigned issues or consider creating one using these guidelines https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
@palisadoes If I am not wrong was this not fixed by -> https://github.com/PalisadoesFoundation/talawa-api/pull/998/commits/93e01bd16384255296659f125f4cc732eb0e2a82 this commit of this PR ? 

I was getting the same error on that PR and it was because of `uploadImage.ts` so I put all fs mutations in try catch block which seemed to get rid of the error then.

Is the error still there?

**Comment by palisadoes** [comment]
1. Yes it's still happening. 
1. There is no `/images` directory in the repo. 
1. There is `/images`. Also we should not be uploading images into the code tree.

**Comment by kb-0311** [comment]
1. I highly doubt the error is from `isAuthSpec.ts` as it is the last test executed perfectly before the ENONET error. Even in my PR where the tests were failing, the main problem was not that file.
2. I think the main problem is in the uploadImage.ts file since I wrote the code to create the /images directory there for testing purposes. And for some reason it is inconsistent still if we have records of it still happening. 
4. @xoldyckk and I coordinated the directory structure as well after which the tests seem to pass. So I also doubt it is because of `src/server.ts` since the actual ENONET error path is -> `'/home/runner/work/talawa-api/talawa-api/images/image.png'` the image.png is a mock file created in and used only for testing purposes in `uploadImage.ts` and delete afterwards.

>[This is an example of one such failed test run.](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4097595336/jobs/7066087060)

After this and #1007 were merged I am curious whether the error was thrown in some other PR also (if yes could you pls link the action run), or locally instances or both , we need to know for sure to see what is the exact problem here. 

@xoldyckk DO you have any input here as well?

**Comment by palisadoes** [comment]
An example of the failed action is linked in the issue's comment

**Comment by kb-0311** [comment]
@palisadoes Yeah I know, I was the author of that PR, and what I am saying is that in the commit after the failed test here after you told me to look into it,  ->https://github.com/PalisadoesFoundation/talawa-api/pull/998#issuecomment-1416793683 , I was sure I had fixed it so in the end all the tests had passed.

Here is the original PR -> https://github.com/PalisadoesFoundation/talawa-api/pull/998  as you can see the tests are passed
this PR was a complementary PR to #1007 ,
https://github.com/PalisadoesFoundation/talawa-api/pull/1007#issuecomment-1416807391

That's why I was asking for instances after the tests throwing this error after that merge.

**Comment by palisadoes** [comment]
I'll close this and if it returns I'll reopen it

**Comment by kb-0311** [comment]
@palisadoes sounds good to me.

@KrutikaBhatt Sorry about this one, I hope you did not beat yourself up over this issue. You can look for other issues to get assigned and contribute to.

**Comment by palisadoes** [comment]
@kb-0311 It's happened again. This needs to be resolved please see this run:
https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4137414342/jobs/7152552533#step:7:168

**Comment by palisadoes** [comment]
![image](https://user-images.githubusercontent.com/16875803/217919175-8e8d0848-a1fd-4261-ad50-5b66da45c979.png)

![image](https://user-images.githubusercontent.com/16875803/217919265-1f75de81-ad9e-4e81-9f7f-a4c1bd2c1d10.png)

![image](https://user-images.githubusercontent.com/16875803/217919345-9d90256e-9010-44b8-ab83-a254b224fb43.png)

**Comment by kb-0311** [comment]
@palisadoes The reason it failed here is that  `writeFIle`  , `createReadStream` are asynchronous methods and so for that, to correctly execute in vitest , it needs all the other tests to pass, as weird as it may sound otherwise vitest cannot track it hence , unhandled.

Source - https://github.com/vitest-dev/vitest/issues/1692#issuecomment-1307610504

In that test run, there were other tests that were failing and hence the file handling error was thrown.  

I am gonna ask in this thread about the best possible approach to tackle this.

**Comment by kb-0311** [comment]
Ok nevermind, got a possible fix in the comment itself, but I needed to add an extra parameter in the vite. config.ts file and another file for this to work

**Comment by xoldyckk** [comment]
@palisadoes that tasksByEvent error is cuz of incorrect logic within `tasksByEvent.spec.ts` itself.

**Comment by xoldyckk** [comment]
@kb-0311 tasksByEvent test probably failed because you changed the logic for getSort function and it no longer returns a sort object expected by tests when `args.orderBy === undefined`.

For example previously `args.orderBy === undefined` would've resulted in `getSort` returning `{ deadline:  -1 }` as the sort object. But now it returns `{ }`. Since you didn't refactor the tests relying on that logic that's probably why this error occured.

You have to remove all the test blocks that rely on this logic like this one:- 
```
returns list of all tasks with task.creator === args.id and sorted by descending order of task.deadline if args.orderBy === undefined
```

**Comment by kb-0311** [comment]
@xoldyckk Oh yeah, that is one test suite I missed while removing that orderBy=== undefined test. Which will be fixed in that same PR. Thanks for bringing that up. 

I think the main problem was that even though a separate test suite failed the unhandled error was thrown for the image file generated in vitest for `uploadImage.ts`.

https://github.com/PalisadoesFoundation/talawa-api/issues/1010#issuecomment-1424756306
