### ISSUE TITLE
Images are not being saved at several mutations

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-api#1091]
**Describe the bug**
Images are not being saved at several mutations.

**To Reproduce**

These mutations have incomplete file upload functionality

1. addOrganizationImage
2. addUserImage
3. createPost
4. signUp
5. updateUserProfile

**Expected behavior**
Files should be saved in Database and images folder in the root folder.

**Actual behavior**
Server not storing the image in database or in root folder.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishav-jha-mech** [comment]
Please assign this issue to me.

**Comment by palisadoes** [comment]
@kb-0311 How does this fit in your plans for fixing image management?

**Comment by kb-0311** [comment]
@palisadoes pls check the slack channel. I think we should discuss more about the file storage a bit before we go about applying this thing

**Comment by kb-0311** [comment]
@rishav-jha-mech @palisadoes _Sigh_, yeah, dude I know,  I deliberately did not add them to all mutations. This is because this is only a temporary solution. check this out ->

https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1441179015

A few thoughts here about issues and PR courtesy  ->

There have been times when my issues or PRs hell even ideas were in conflict with other PRs or even comments before I create them or after I create them in which cases I either negotiate with the authors (when I have good reason to do so ) or simply usassign myself , or close the issues and PR. To ensure that does not happen there are a few unspoken rules not in CONTRIBUTING.md followed by me and other contributors. 

Because we cannot just always ask Peter to fix these kinda quarrels there are other more important things he might be busy with. 

Pls take this as genuine feedback and not raising any kind of hostility towards you.

1. More often than not when a developer is working on a function, creates the function but does not apply it everywhere needed it is because of some good reasons. Here in this case, because this is a temporary solution and will be changed so does not make sense to implement it right off the bat everywhere and write the tests for them and then change everything again.
2. In the cases where you feel your potential issues could be an extension or in conflict with other PRs it is important to ask the author of the PR in slack channel or in their PRs themselves why he/she did not write code for stuff which is very easy. Here, I applied the utility I created to `createOrg` mutation which is like a 2 line change in that file so there must be a reason for me to not make 2 line code changes in every mutation, right? 
3.  It is not mentioned in the contributors' guidelines but it is good practice to let the person who created a function apply and test that function when needed. This is basic courtesy the new contributors who started contributing 1-2 months ago are following . Like an unspoken rule a bro code per say.
4. There is a long and I am not exaggerating when I say looonnng list of potential bugs I have noted down on my notepad for the API  but I cannot directly open them without discussing them on the slack channel first in case of ambiguity/conflict or other reason no matter how small to make sure the workflow is stable. 
5. Check out my merged PRs, especially the #1065 and #1073 

https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+author%3Akb-0311+is%3Aclosed

Here you will realize this is the exact thing I am talking about in point 1.
6. So yeah my advice would be when your issue are related to any other recent PRs pls make a point to ask the author of the PR  why certain things he did not do which required minimal effort on the author's part. 

Although for now this issue can be closed depending on the convo I am having with Peter about a more permanent strategy. Either that or I ask you to please un-assign yourself and assign me to work on this issue when I feel there is a need to implement it when a permanent strategy will take a long time. 

I completely get you are trying to help and we are all learning and that is completely fine no worries :v:

**Comment by rishav-jha-mech** [comment]
This is an issue, i found it, i raised it. Its not that i have an permanent solution right now, there's something that's missing, and others should know, that file uploads don't work, because for 3 days i tried different ways to upload files and it didn't work, i thought the problem is with my system. I don't want others to be stuck on the same problem.

Closing this issue may cause problem to other contributors, its better that i unassign myself.

**Comment by kb-0311** [comment]
@rishav-jha-mech I am pretty sure most people working on the client apps know that content uploads do not work. Why? because it has never worked and it is not because of your system.

Long answer checkout this comment: https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1434149051

There was also a community call, a few days ago going through the talawa mobile app and the main problem was exactly the content upload thingy.

I have been working on strategies for a more permanent solution for a month now. So I was asked on call to implement a temporary solution for this problem so that clients can at least use the image uploads. hence this issue.I did not go ahead completing this all at once to not cause any breaking changes.

**Comment by kb-0311** [comment]
@palisadoes you can either close this issue or assign it to me. 

Depending on priorities - whether you want me to work on permanent solution or implement this temporary fix.

**Comment by rishav-jha-mech** [comment]
@kb-0311 client apps ?, as you already know the code is written in the backend for uploading images, there is package present for it and also uploadImage function is already present, now as if all of it is there it should work ?, but it doesn't. 

You are right, image upload thing never worked, because they were never sent from the client side in talawa-admin. And when they were sent the server was getting hung, Usually no one expects that something is written in the backend which does not work, and that's were  i was wrong.

**Comment by kb-0311** [comment]
>as you already know the code is written in the backend for uploading images, there is package present for it and also uploadImage function is already present, now as if all of it is there it should work ?, but it doesn't.

1. Did you properly read the linked comment in the last message on this thread? the package you are mentioning is `graphql-upload` .
2. The uploadImage function does not work now. And is basically placeholder logic till a proper way to handle images is done. I do not even know why you brought it up since it does not even do encoding or decoding thingy.

>You are right, image upload thing never worked, because they were never sent from the client side in talawa-admin. And when they were sent the server was getting hung,

That is because the Upload scalar is not getting resolved at runtime now Why? because the package responsible for runtime resolving the Upload scalar is the `graphql-upload`. Could I go ahead and fix that so that Upload Scaler work as it is supposed to? Probably. Should I go ahead and do it? NO. Because right now there is a conversation about migrating to `graphql-yoga` server from apollo which can cause breaking changes for this functionality. 

SO this solution does not use the Upload Scalar at all.

>I don't think anyone would expect that something is written in the backend which does not work, and that's were i was wrong.

Why not? The project is still is development phase. Plus a coming up with a consistent permanent solution for binary data storage is not easy.

**Comment by rishav-jha-mech** [comment]
I'll open a PR for it soon for createOrg function, thanks for explaining everything in such detail.

**Comment by kb-0311** [comment]
@rishav-jha-mech yeah no problem.

**Comment by rishav-jha-mech** [comment]
@kb-0311 bro its not working again (createOrganisation image upload)💀, i have checked it several times since morning. It was working yesterday when your pr got merged, ig it has something to do with the latest merge.

**Comment by kb-0311** [comment]
@rishav-jha-mech yes it not working is unrelated to my PR make sure both of the projects are synced wit the latest commit/ if still does not work then try to ask @EshaanAgg about it.

**Comment by palisadoes** [comment]
You guys need to chill. There are two issues that have led to this situation.

1. Frustration with teammates' efforts
1. Insufficient communication to provide context

We had an unusual situation today where miscommunication caused a PR to be merged prematurely. This caused the participants to accelerate the merging of a sister PR to reduce the amount of time of disruption.

The nature of the changes were discussed in issue comments, but apparently not relayed adequately to other repositories' slack channels to alert them of any potential impact.

Our CONTRIBUTING.md files will need to be updated to cover communication with stakeholders in other repositories of possible upcoming breaking changes.

Regarding communication in general: we try very hard to keep a professional approach with our interactions. We try to be fair but firm. You showed dominion over firm, but forgot fair. 

This software promises to unite communities and it won't happen if our community is divided.

**Comment by anshgoyalevil** [comment]
@palisadoes @kb-0311 @rishav-jha-mech 

In my opinion, we should not rush out the things, and think of a unified approach to the current issues. We can have a G-Meet or something like that, to discuss the right approach to the image upload issue.

Let's work like an open source community, and give everyone a chance to prove themselves. After all, we are using GitHub, a version control system, where things can be reverted in case something goes wrong.

**Comment by rishav-jha-mech** [comment]
@anshgoyalevil I agree with you, we should discuss this over a meeting.

**Comment by kb-0311** [comment]
@anshgoyalevil @rishav-jha-mech did you two not join the file-sotrage-discussion channel?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil @rishav-jha-mech did you two not join the file-sotrage-discussion channel?

Just joined from your invitation. Thanks!

**Comment by kb-0311** [comment]
@palisadoes for now I think you can close this.
