### ISSUE TITLE
Bug Report: Create a common helperFunction `getInputArg()` And Add tests for Query/getDonationByOrgIdConnection 

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-api#1149]
**Describe the bug**
The code for generating inputArgs by creating `getInputArg()` function in many different query/mutation resolvers is creating a repetition of same code.
Instead, we can create a common `getInputArg()` in helpFunctions just like, we did for `getSort()`.
Also, add tests for `getDonationByOrgIdConnection.ts`

**Expected behavior**
A common `getInputArg()` helperFunction with no repetition of code.

**Actual behavior**
Repetition of code exists.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
@xoldyckk @palisadoes I wanted to take your opinion here. I was trying to solve this issue but had one problem here.
Some inputArgs are object specific i.e. those inputArgs are only used in the specific resolver only.
For example,
`usersConnection` has a inputArg `where.admin_for`.

Now the question is, should these args be also placed in a common helperFunction `getInputArgs()`?

**Comment by xoldyckk** [comment]
@beingnoble03 I'm against the idea of a common function for sort and filter functionalities for different resolvers unless it returns output according to input and the output is also type safe. So, basically if you're passing in filters/sort for a particular resolver, it should be guaranteed that it only returns the corresponding mongoose filters and sorts for that resolver, and we also get typescript's type safety somehow(means we know what properties those sort/filter objects can contain before using them).

Currently for sorting it works, because sort only returns an object with a single field, so there's no margin for error(because what you pass in for input determines the single field that returned object will contain).

For filtering the same implementation isn't easy, because filter adds/appends fields to that returned object. So, fields unrelated to a resolver might get added to that object. Also, the returned object needs to conform to the filter shape for individual resolvers. If this isn't done, using typescript is meaningless.

**Comment by beingnoble03** [comment]
@xoldyckk yes, you are right. Creating a common function here, is only going to create things complex and can bring some unwanted errors.

So, Is there any way we can limit the repeated use of some common fields like id, name, title, description etc?

There's one approach by introducing different `helperFunctions` like `getInputArgsForId()`, `getInputArgsForName()` and so on...

What's your opinion on this?

**Comment by xoldyckk** [comment]
@beingnoble03 Nah that's very ugly and confusing. If you're doing it, you'll have to do it using a single function.

Also I feel many of the filters and sorts provided to clients are useless and database intensive as they're not indexed.

**Comment by beingnoble03** [comment]
@xoldyckk But creating a single function has a problem. The problem is that we can't tell which inputArgs are included in the function simply by looking at the function's name. Also, the error you mentioned earlier will remain.
> For filtering the same implementation isn't easy, because filter adds/appends fields to that returned object. So, fields unrelated to a resolver might get added to that object

For example, if someone is creating a resolver and wants to use the common inputArgs helperFunction, he would have to look into the helperFunction to confirm whether the inputArg he wants is included in helperFunction or not.

**Comment by xoldyckk** [comment]
@beingnoble03 The function can include a multitude of input args of different types. What it returns can be determined by a generic type which can be passed in while calling the function.

**Comment by beingnoble03** [comment]
@xoldyckk Got it. So, do we need to define an interface in every resolver in which we will be using the helperFunction?
Should the interface look something like this?
```typescript
interface Interface_InputArg {
  _id?: any;
  title?: any;
  description?: any;
  organization?: any;
  location?: any;
  status?: any;
}
```
This example's for the `eventsByOrganizationConnection`. Please clarify.

**Comment by xoldyckk** [comment]
@beingnoble03 Yeah, I guess so. Those `any` won't be accepted though.

**Comment by palisadoes** [comment]
@beingnoble03 How close is this to completion? It's marked as inactive yet there is ongoing discussion in the PR.

**Comment by beingnoble03** [comment]
@palisadoes I've addressed the reviews just now. Sorry for the delay.
