### ISSUE TITLE
Optimising Mutations for [Many] Action

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#115]
All the remove/update mutation only performs action on one data. 
Some of the mutations can be optimised so that actions could be performed on multiple data points with single graph api

Some examples can be:
1. removePosts
2. removeComments
3. removeTasks
4. removeAdmins

**Comment by sumitra19jha** [comment]
Will this be beneficial for the application? @Laurell876

**Comment by iamsaumya** [comment]
@sumitra19jha I see the point you are trying to make and I think adding the resolvers to delete multiples will be only useful when we have the option to delete multiples in the App. 

Adding to that, I don't think `removePosts`, `removeComments` and `removeAdmins` should exist because these are high impact mutations and the user should be prompted to delete them one by one. Does twitter allow you to delete tweets at the same time? 

I am not sure about `removeTasks` though.  

Thanks!

**Comment by sumitra19jha** [comment]
Hi @iamsaumya :)
Saumya in-fact i was thinking about the same thing when creating the issue. If you refer to the idea list [here](http://www.palisadoes.org/gsoc/ideas/), then you can see that the foundation is thinking on group chats and improving interface design and experience. Some apps include remove or add many(Whatsapp Group)  functionality while some don't. So I thought maybe @Laurell876 can suggest us whether these modification will be beneficial now or maybe in the future.

**Comment by iamsaumya** [comment]
I agree with you sumit, that's why I said I am not sure about `removeTasks`.

**Comment by palisadoes** [comment]
@sumitra19jha please close this if you are not working on it
