### ISSUE TITLE
Decreasing length for the orgization Name 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-api#1160]
**Describe the bug**
 As now we are rendering name of the organization on the dashboard, having large name will break the styling.
 Right now the characters allowed are 256 , we are trying to reduce it to 50 as per the discussion

**To Reproduce**

1. create an organization
2. give it a big name
3. open dashboard of that organization
4. see the error

**Expected behavior**
decreasing the length for the orgname and make changes in the error messages accordingly.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@noman2002  can you please assign this to me.

**Comment by anshgoyalevil** [comment]
@aashimawadhwa 

We shouldn't reduce the lengths to less than 256 characters. 

Reducing names to a value like 50 is not a good practice, since styles need to be responsive.

Think of a mobile device. A string of length 50 will break the styles too, while on a large screen, like 42 Inches, A string of 500 characters would be perfect.

Hence, we should focus more on creating responsive styling instead of reducing the length validations.

Even WordPress and other publishing software allow strings of ANY length. Styles break there too, but that is the problem with the person who entered that much big string.

**Comment by aashimawadhwa** [comment]
@anshgoyalevil  the major concern is no tittle is 256 characters long , 256 characters are roughly 25 words and since there's been a change in design that' is we're rendering the name of the organization on the navbar that is causing the issue.

In mobile views the responsiveness can be fixed, but primarily the behaviour is not correct on standard screen size that on 1200 or 1440.

@noman2002  wdyt?.

**Comment by kb-0311** [comment]
>As now we are rendering the name of the organization on the dashboard, having a large name will break the styling.


@aashimawadhwa 

1. the maximum character limit which currently exists is not because of styling reasons it exists to limit the payload stored in the DB to not overload the 16MB doc size restriction of MongoDB or cause overhead.
2. The API does not exist to fix UI or CSS errors, it is to handle mutation and logical errors. That is the job of the front-end CSS peeps. 
3. You are saying that responsiveness can be fixed on mobile screens but you want to change the API behavior for larger screens instead of fixing responsiveness in the admin portal on the front for larger screens ... what? You don't find that contradicting? lol.
4. You are saying 256 words are approximately 25 words and mostly no organization is that long but that is the upper limit which covers 99% of organization names that could be created. I can find many examples of potential South Indian organizations(lets take) >=25 words. Reducing it to 50 or any other arbitrary number would be UX error-prone at worst and useless at best.

But maybe I am being pedantic and a little annoying here for this issue but I think @xoldyckk could clear it up for me. What are your thoughts on this?

>Right now the characters allowed are 256, we are trying to reduce it to 50 as per the discussion

Also, Could you link the discussion could be that I am misinterpreting the problem here? That would be very helpful.

**Comment by xoldyckk** [comment]
@aashimawadhwa @anshgoyalevil @kb-0311 Limiting the maximum/minimum number of characters for inputs on api side is a good design. But the upper/lower limit should be carefully considered and depends on many factors. For something like title of an organization let's consider a few things:-

1. A title with extremely long length(like in the ranges of 100000 characters) doesn't make sense. No sane/practical organization would want to have a title that long.
2. Title for an organization can never be just an empty string or null. It must always be at least 1 character long.
3. If your application supports localisation and internationalization, you have to consider that characters in different languages mean different things according to their placement, length of a sentence in english will not be the same as the length of a word in something like chinese(maybe an english sentence taking 50 characters takes 200 characters in chinese) etc.

These are some of the important factors many more can be listed. Still, after a careful study you can reach a general consensus for what the upper/lower limit for something like length of the title for an organization should be.

Regarding how it's displayed on the UI, it's the job of the developer on client side to make strings of any length comply to their UI's design. It's not the job of the api to employ constraints to inputs just to favour a simple UI behaviour like this one.

For the problem you're facing a simple fix is to just trim the title if it's too long, and provide an expand(read more) button to view the complete title.

**Comment by Cioppolo14** [comment]
@aashimawadhwa Would like to edit this issue or a create a new one if the concensus is the that the resolution should be to "trim the title if it's too long, and provide an expand(read more) button to view the complete title"? Rather than limit the characters.

**Comment by aashimawadhwa** [comment]
I will edit this one , just had few more doubts after clearing them. @Cioppolo14

**Comment by aashimawadhwa** [comment]
@xoldyckk  will read more look good in the dashboard navbar? is it a good design practice?

**Comment by xoldyckk** [comment]
> @xoldyckk will read more look good in the dashboard navbar? is it a good design practice?

That's for you to worry about and how you display organization's title. The simplest approach is to trim it. It's the organization owner's fault making it so damn long. It's common sense to not have a ten line title for your organization.

While creating the organization you can display a warning, that the title organization creator has entered is too long, and it might not fit correctly in all UI implementations and that it'll probably be trimmed.

Also, the thing about min/max limit for organization title, first discuss it for the constraints I told you before.

**Comment by xoldyckk** [comment]
@aashimawadhwa What you're asking for is called semantic input validation. If it's going to be done, it needs to be done for inputs in all query/mutation resolvers, not just for organization's title. 

There are many fields other than organzation's title which need semantic validation. For example title/description of a task, title/description of a post, title/description of an event etc. Those are just some of the examples.

And not only the validation, there also needs to be a bulletproof and elegant way of communicating those errors back to client, using graphql.

**Comment by aashimawadhwa** [comment]
Oh I see, i would love to work on the future issues regarding this.
