### ISSUE TITLE
Feature Request: Implement Audit Trail Fields in Schema

### ISSUE THREAD

**Issue by LakshyaSatpal** [PalisadoesFoundation/talawa-api#1479]
**Is your feature request related to a problem? Please describe.**
Currently, the schema doesn't have basic audit trail features

**Describe the solution you'd like**
Adding `createdAt`, `updatedAt`, `createdBy`, and `updatedBy` fields to each collection in the database. The goal is to automatically capture and store information about when and by whom a record was created and last updated.

**Comment by LakshyaSatpal** [comment]
@palisadoes @xoldyckk 

I wanted to clarify, `createdBy` and `updatedBy` will be specifically a `User`, right? 

For `createdAt` and `updatedAt`, we can just do `{ timestamps: true}` in the schema. We can remove the manually handled `createdAt` field in some models, then.

**Comment by xoldyckk** [comment]
@LakshyaSatpal i don't see the need of `updatedBy` field. `createdAt/updatedAt` fields, do it however u see fit. Instead of `createdBy`, it should be named something like `creatorId`. 

One thing to notice is that not every single database schema/table references a user directly. The relations could permeate indirectly as well, so a `creatorId` field is not needed directly on each type of collection.

**Comment by palisadoes** [comment]
Tracking the id for the user that did the update will help with auditing for Admins. We should add it.

**Comment by LakshyaSatpal** [comment]
Got it, Thanks.

**Comment by LakshyaSatpal** [comment]
still working on this. Will try to wrap this up asap. Commenting to not mark this as stale.
