### ISSUE TITLE
Incorrect script behavior when modifying .env parameters

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-api#1590]
**Describe the bug**

I noticed unexpected behavior in the script when modifying or removing parameters in the `.env` file. The script fails and there are issues with the handling of commented and removed parameters.

**To Reproduce**

1. Comment out a parameter in the `.env` file using `#`.
2. Remove a parameter completely from the configuration.
3. Delete the `.env` file

**Expected behavior**

The `setup script` encounters issues when handling `commented` or `removed parameters`, leading to errors. Key points include:
- No errors when removing a parameter.
- Preservation of comments in the `.env` file.
- Automatic creation of the `.env` file if it doesn't exist.

**Actual behavior**

- The setup script dose not preserve comments.
- The setup fails when handling removed parameters in the `.env` file. 
- User is prompted to `copy the contents from .env.sample` if the `.env` file is missing or some of the parameters are missing from the file.

**Comment by Doraemon012** [comment]
@palisadoes Please assign this to me.

**Comment by palisadoes** [comment]
https://github.com/PalisadoesFoundation/talawa-api/pull/1569

You worked on this already. This means your work was incomplete.

We merge develop into main periodically when we feel develop is stable. If the error is not in the `develop` branch it is not a valid issue.

Closing, unless this issue is in the develop branch and we can reopen it
