### ISSUE TITLE
API - Remove Support for Private Organizations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1604]
**Is your feature request related to a problem? Please describe.**
We need to reduce and simplify some of the Talawa features. 

The concept of private organizations is unlikely given that most organizations using Talawa will be non-profits where transparency will be important.

**Describe the solution you'd like**

Remove all support for private organizations in:
1. Backend systems and supporting code

Other:

1. All tests must be valid and pass
1. No other functionality must be affected.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1604
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327
3. https://github.com/PalisadoesFoundation/talawa/issues/2287

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AVtheking** [comment]
Can I work on this issue ?

**Comment by palisadoes** [comment]
@AVtheking What's the status on this? We have other PRs dependent on this change being implemented

**Comment by AVtheking** [comment]
I have created a pr for this please review it.

**Comment by AVtheking** [comment]
I have created a new pr

**Comment by palisadoes** [comment]
Please refer to this discussion before proceeding
- https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274

**Comment by Farhanpathan0007** [comment]
Is this issue still unresolved, and if so, am I able to take on the task?

**Comment by aialok** [comment]
@palisadoes, we should update `isPublic` to `'userRegistrationRequired'` in the `'sample-data' `and `'schema.graphql'` files in talawa-api. Otherwise, it may lead to bugs or test failures, and individuals importing the sample data might encounter difficulties.

![Screenshot from 2024-01-14 13-27-21](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/88382993-2d16-4f07-8852-1444c683aa5e)

![Screenshot from 2024-01-12 11-38-13](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/e23104f9-4589-4c82-93c1-1432657bf788)

**Comment by palisadoes** [comment]
An issue has been created to fix the DB importation and add it to the GitHub action workflow
- https://github.com/PalisadoesFoundation/talawa-api/issues/1685
