### ISSUE TITLE
Create GitHub Action to Import Database for PR Testing

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1685]
**Describe the bug**

1. Running the command `npm run import:sample-data` fails
2. This is due to an update in the DB schema which is not compatible with our sample data
3. We also don't have the ability to automatically test the command as part of our PR approval process

**To Reproduce**

1. Run `npm run import:sample-data`
2. Failure

**Expected behavior**
 
1. The sample data must be modified to accommodate the new DB schema where the `userRegistrationRequired` field now replaces the `isPublic` field. The logic of `userRegistrationRequired` is opposite of `isPublic` therefore `True` will replace `False` and vice versa for these fields in the data update.
    1. Data importation must succeed without error
1. A GitHub must be created to import the data as part of the PR YAML file.
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml
    1. This must occur after running the test suite and before the code coverage is calculated
     1. The GitHub action pass this stage of the workflow

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- https://github.com/PalisadoesFoundation/talawa/pull/2322#issuecomment-1890647988
- https://github.com/PalisadoesFoundation/talawa-api/issues/1604#issuecomment-1890876772

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I would love to work on this issue. as I already work on the above issue in talawa admin.

**Comment by aialok** [comment]
I checked why the test failed and found the issue in the `talawa-api` repository, not `talawa-admin`. The problem is that the workflow is cloning the `main` branch of `talawa-api`, in which schema.graphql is not up to date as changes are done in develop branch, because of this userRegistrationRequired is not present in the schema.graphql, causing the test to fail.

Here's the workflow file:
![Workflow File](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/172b1328-54f5-4234-baea-83c2bc6ed7f3)

Here's the `schema.graphql` file:
![Schema.graphql](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/785cd845-155d-44e1-8162-f9c8fe5698be)

And the failing GraphQL inspector:
![Failing GraphQL Inspector](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/d7bb8707-76d8-448e-ba1b-ef5e9667b22e)
