### ISSUE TITLE
API Issue for "Profile Update Not Working on Admin Portal #1508"

### ISSUE THREAD

**Issue by Shubh152** [PalisadoesFoundation/talawa-api#1834]
**Describe the bug**
Any Changes to The Admin Profile cannot be made . We get a 404 error in response.

**To Reproduce**

1.Log in Admin Panel as Admin
2.Go to Update Profile section
3.Change Profile Details
4.Click Update Profile

**Expected behavior**
Profile Information Should be Updated

**Actual behavior**
Response is error

**Screenshots**
[300257818-9d263248-15f8-4964-be7f-2b9f36166795.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/121512095/ae1690d4-4220-4a8a-8b02-c3f95e69a166)

**Additional details**
Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1508

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shubh152** [comment]
Please assign this issue to me. I have made all the changes in the admin and api repo.

**Comment by Cioppolo14** [comment]
@Shubh152 Because these 2 issues are connected, I am going to give you a 3rd issue.  If the issues/PRs end up slowing down your progress, we will need to drop one. Our usual policy is to have 2 or less issues, with some unique exceptions.  I think this particular circumstance qualifies as long as the 3rd issue doesn't slow you down.

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.

**Comment by palisadoes** [comment]
1. Same as #1750
1. Closing
