### ISSUE TITLE
Test: Create tests for src/resolvers/Mutation/updateAdvertisement.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2055]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Atharva-Kanherkar** [comment]
Hi @palisadoes May i work on this?

**Comment by palisadoes** [comment]
What's happening with this issue? Have you stopped working on it?

- https://github.com/PalisadoesFoundation/talawa-api/issues/1588

**Comment by Atharva-Kanherkar** [comment]
> What's happening with this issue? Have you stopped working on it?
> 
> * [Create Support for Event Agendas #1588](https://github.com/PalisadoesFoundation/talawa-api/issues/1588)

@palisadoes Sir I have a lot of code ready for the admin panel. The issue is i have the login error where i can not login using any of the login credentials provided. It seems to be a local error, but a lot of people in slack helped me, even usign remotely hosted API links, but it just did not work. I need to test the changes visually before making a PR. I have almost all of the code ready, but making a PR without testing it visually would not be a good practice. I am arranging a different machine to test my changes, so that i can make a PR. Does that seem okay?

**Comment by Cioppolo14** [comment]
@Atharva-Kanherkar That sounds good, how long do you think that will take?

**Comment by Atharva-Kanherkar** [comment]
> @Atharva-Kanherkar That sounds good, how long do you think that will take?

 I can make a PR within a week. Can you please re assign me the issues?

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Sir, what about the issues [1779](https://github.com/PalisadoesFoundation/talawa-admin/issues/1779) and and 1778? Can I keep working on them?
