### ISSUE TITLE
Add support for eventsAttended

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-api#2088]
**Is your feature request related to a problem? Please describe.**
Currently, it's difficult to gain a comprehensive understanding of a member's participation history within the organization.

**Describe the solution you'd like**
 I propose adding an `eventsAttended` field to the user schema. This would provide a streamlined way to track each member's engagement level and identify patterns in their event attendance.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/63ba8c7b-6dc7-4cc1-86cb-7c09f5cbedde)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@Cioppolo14 I wanna work on this issue

**Comment by meetulr** [comment]
@palisadoes @duplixx can we work on issues related to the gsoc project?
e.g. I have proposed solutions for issues like this in my proposal, can we start creating issues for the same? Just asking😅

**Comment by varshith257** [comment]
@meetulr It isn't a good idea to work on GSOC issues before selected mentees are announced. Once mentees are announced we can actively work towards it.

**Comment by meetulr** [comment]
@varshith257 right? that's what I thought, and we were advised the same in the GSoC meet too. But this issue is directly concerning the event attendance project, that's why I asked😅.

**Comment by varshith257** [comment]
I think we can close this issue as not planned. Once GSOC mentees are announced the selected mentee can work on this issue.

**Comment by meetulr** [comment]
@palisadoes @duplixx views?

**Comment by duplixx** [comment]
@meetulr @varshith257 This solution enhances the user schema, for tracking members attended events. As mentioned in the GSOC ideas, we can address  API dependencies beforehand so that implementation becomes easier when mentees are announced, yeah its not userTypeFix related issue

**Comment by meetulr** [comment]
@duplixx 

Enhancing the project in any way is good, but we were advised not to work on GSoC project issues in the meeting. That's why others are not creating issues for those, otherwise everyone would have, right?😂.

And this project expects changes in both admin and api repos, as mentioned in the `Repos to update`, so yeah there would be api dependencies😅

As @varshith257 mentioned, I think we should start working on these after getting selected (this was mentioned in one of the videos I think, maybe last year's introductory meeting🤔), this way everyone would have a fair chance.

Let's await Peter's input before we go further.

**Comment by palisadoes** [comment]
1. We should close this. 
2. We created some API issues to support potential GSoC ideas before the list was posted. This was done because without this foundation some of the ideas would have been very difficult, if not impossible, to complete during the period.
3. We have tried hard not to create additional issues that would impact GSoC after the list was posted for the conflict mentioned in the discussion.
4. New issues created by our volunteers have focused on fixing obvious deficiencies to:
    1. rectify broken design (`userType`, recurring events, event projects), 
    2. add user and organization data to the database that would be useful to Admins and Members alike,
    3. standardize the UI/UX in the Talawa-Admin screens
5. New issues have also been created to add intuitive, usable features that we felt people would  want (Action items, Volunteers, Event Agendas).

The activity this has generated will be useful when our mentors evaluate a person's ability to successfully complete their GSoC project. This was stated in the kickoff meeting. We also hope that the activity will encourage all our new contributors to continue participating in the repos beyond the announcement. 

Over the past 12 months, the code has become more stable and feature rich, and hence usable. In the kickoff, we also mentioned our MVP goal. We couldn't achieve this without `userType` being fixed. We can't get there without our current slate of GSoC ideas being complete either. There is a lot of cleanup work work to be done to support this too, such as more reusable UI/UX components and a cybersecurity review of the code base. We hope to achieve this goal in the near future. We can only achieve that together. GSoC is only part of the story.
