### ISSUE TITLE
[userTypeFix] [BUG] organizationsMemberConnection has major issue

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2157]
**Describe the bug**
`organizationsMemberConnection` query has `appUserProfileId` which returns null always.

**To Reproduce**

1. Make a query on it with some variables
2. Other info like firstName etc, along with `appUserProfileId`
3. Gets null 

**Expected behavior**
It should return the appUser data as per new update

**Actual behavior**
Always returns `null`

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/76914348/da7200bd-39e9-4c09-88cf-f8db1ae54af5)
@pranshugupta54 @palisadoes Can you please say if I am missing something here. Because according to this query the AppUserProfileIds are coming for users. Thank You.

**Comment by Anubhav-2003** [comment]
Also I am happy to solve this, as others are busy. Thank You.

**Comment by pranshugupta54** [comment]
@Anubhav-2003, try doing `isSuperAdmin`

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, The addresses of the users are not part of the sample data. But part of the userModel. Is it as per intentions or a mistake? Do we now require address for users or is it deprecated?

**Comment by pranshugupta54** [comment]
@Anubhav-2003, we do have Address (line1, city, state, country) in MemberDetail screen (user settings) so it's still used.

**Comment by Anubhav-2003** [comment]
@pranshu

> @Anubhav-2003, we do have Address (line1, city, state, country) in MemberDetail screen (user settings) so it's still used.

Ok then it must added to the sample data.  Because the sample data is a representation to test out all functionalities. I will add it then. Thank you for the info.

**Comment by Anubhav-2003** [comment]
> @Anubhav-2003, can you try run the following Query:
> 
> ```
>   query Organizations(
>     $orgId: ID!
>     $firstName_contains: String
>     $lastName_contains: String
>     $event_title_contains: String
>     $first: Int
>     $skip: Int
>   ) {
>     organizationsMemberConnection(
>       orgId: $orgId
>       first: $first
>       skip: $skip
>       where: {
>         firstName_contains: $firstName_contains
>         lastName_contains: $lastName_contains
>         event_title_contains: $event_title_contains
>       }
>     ) {
>       edges {
>         _id
>         firstName
>         lastName
>         image
>         email
>         createdAt
>         appUserProfileId {
>           adminFor {
>             name
>           }
>           isSuperAdmin
>         }
>       }
>     }
>   }
> ```

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/76914348/a5664e9f-5329-484f-880f-be154ff4d945) Yes I ran it.

**Comment by pranshugupta54** [comment]
@Anubhav-2003, I'm still getting this issue:
<img width="1127" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/a9d1b7c4-2534-4704-8b24-258b70552ab7">

**Comment by Anubhav-2003** [comment]
@pranshugupta54 
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/76914348/c2e55df0-1fa3-47f9-be3b-ac508ae6178d)
As you can see it is working properly. Kindly pull the latest upstream. Maybe you are doing something wrong somewhere. Thank You.

**Comment by pranshugupta54** [comment]
Ohk, it's an issue with `first` and `skip`. It throws that error when u don't send them

**Comment by Anubhav-2003** [comment]
> Ohk, it's an issue with `first` and `skip`. It throws that error when u don't send them

Those are required parameters. Thank You.

**Comment by pranshugupta54** [comment]
> Those are required parameters. Thank You.
The error should show required then, instead of non-null issue for appuser

**Comment by pranshugupta54** [comment]
I understand that we have a front-end, but that shouldn't justify having an API with frequent errors. The API should function autonomously, rather than relying on the frontend's functionality. We cannot expect frontend developers to manually handle every required field; instead, we should empathize with them by considering the frustration of encountering unexpected errors in the API after investing hours in troubleshooting, only to discover that a required field wasn't properly flagged.

Like in Posts Query, it shows a very proper error message:
- `Argument first was not provided.`
<img width="1126" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/2cf1a639-8a65-4858-84b9-f55c3503c448">

**Comment by Anubhav-2003** [comment]
@pranshugupta54 what you are saying would only make sense, when it is not instructed what variables to provide. If you look clearly at the screenshot, you sent me. You can clearly see in the query that you are making, the first and the skip variables are present. But you have not provided those arguments in the variables section. In the gql section of the front-end all queries also have the variables written. Therefore, it is expected to send those variables. if a developer is still not able to figure out even after not sending all the variables why the error might be occurring, then he lacks the depth and maturity required to work with graphQL. Because how can you expect to fetch certain number of objects in a paginated query without specifying the number of them you require.

If you still feel that this might be useful, then you can create a good first issue. But for me this issue is solved, all the queries and fields are being fetched properly. There are much bigger problems in the API, the obvious one being faulty implementations. I hope this conversation ends here.

Thank you.

**Comment by pranshugupta54** [comment]
Like you said that we have included `first` and `skip` in Query but not passed it in variables so it's throwing an error, but that's not the issue. Let's take an example without even sending them in Query, only passing `orgId` which is marked as required. We still get an error:
<img width="1382" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/7f4f8d41-fdfa-495a-a4eb-1682bb458c49">

It's a very normal Query which has the required field but still throws some unknown error, how would someone ever know that they require `first` and `skip`? Even if they have experience with GraphQL, they won't assume passing optional fields as required.

**Comment by Anubhav-2003** [comment]
@pranshugupta54 you misinterpreted what I said in terms of the variables first and skip being present in the query and you not sending them in the variable section. I meant you can clearly see them in the query. Them being present in the raw query has nothing to do with the error. I meant that you know that they are needed when you were sending the query in the first place. Now you deleting them would obviously throw an error. I am not new to graphQL to make such a rookie comment.

For front-end developers, all the queries that they require are written in the mutations and queries section of the graphql folder they can always refer there because all of them I guess have the mandatory variables written. And when you say how an experienced developer would know whether to send first and skip, then you should read the last line of the first paragraph of my prev reply, and also the fact that if a developer is experienced in graphQL, then he can simply open the resolver like I did. And in the comments it is clearly written which arguments are necessary. Even I did not know which arguments were required before I started working on this issue. But one glance on the resolver tells you the arguments required.

 As I said, if you feel that this can be helpful, then you can create a good first issue. But for me this issue is solved as the faulty implementations have been completely fixed. Thank you.

**Comment by pranshugupta54** [comment]
Why are you taking this so personally? None of my comments aim to suggest that you lack experience in GraphQL. As I mentioned before, we can't expect everyone to be experienced with GraphQL; we have many beginner developers too. The foundation encourages students to get involved and learn more. A platform is improved not just by having highly experienced developers, but also by having **_better error messages and documentation_**.

How does someone typically use any API? Do they dive straight into the code or do they try to understand it through documentation? If you're asserting that you're very experienced with GraphQL, then you might not understand how frontend developers with less knowledge of GraphQL operate. Most people wouldn't delve into the API codebase to find resolver functions and check their implementation. They would likely use the Query directly and rely on documentation and error messages. So, if they don't see an error indicating that 'first' and 'skip' are required, they may never realize it and end up wasting time.

The main point here is that since 'first' and 'skip' are required fields for this query, they should trigger an error. We shouldn't expect developers to delve into the codebase to check the implementation.

It's not a debate about whether your pull request got merged and looks good to you. If it's merged and you're satisfied, then it's resolved. I never said you didn't fix it properly. My concern all along has been that a beginner contributor to this project won't immediately dive into the resolver codebase to figure out what's required and what's not. Why bother having documentation and error messages if everyone needs to check the code and its function implementation?

Moreover, it's like having an option on the frontend to create an organization which requires Orgname and location, but then it throws some random, unknown error. You then say, "Go check Network console errors for 'org image required'." How would a user know what the error is?


Let's end this debate for now, thank you.


@palisadoes, can you please have a look into this.

**Comment by Anubhav-2003** [comment]
> Why are you taking this so personally? None of my comments aim to suggest that you lack experience in GraphQL. As I mentioned before, we can't expect everyone to be experienced with GraphQL; we have many beginner developers too. The foundation encourages students to get involved and learn more. A platform is improved not just by having highly experienced developers, but also by having **_better error messages and documentation_**.
> 
> How does someone typically use any API? Do they dive straight into the code or do they try to understand it through documentation? If you're asserting that you're very experienced with GraphQL, then you might not understand how frontend developers with less knowledge of GraphQL operate. Most people wouldn't delve into the API codebase to find resolver functions and check their implementation. They would likely use the Query directly and rely on documentation and error messages. So, if they don't see an error indicating that 'first' and 'skip' are required, they may never realize it and end up wasting time.
> 
> The main point here is that since 'first' and 'skip' are required fields for this query, they should trigger an error. We shouldn't expect developers to delve into the codebase to check the implementation.
> 
> It's not a debate about whether your pull request got merged and looks good to you. If it's merged and you're satisfied, then it's resolved. I never said you didn't fix it properly. My concern all along has been that a beginner contributor to this project won't immediately dive into the resolver codebase to figure out what's required and what's not. Why bother having documentation and error messages if everyone needs to check the code and its function implementation?
> 
> Moreover, it's like having an option on the frontend to create an organization which requires Orgname and location, but then it throws some random, unknown error. You then say, "Go check Network console errors for 'org image required'." How would a user know what the error is?
> 
> Let's end this debate for now, thank you.
> 
> @palisadoes, can you please have a look into this.

Mate the only person taking personally is you.  This is an extremely trivial issue which you are elongating Just because you created this issue. I Clearly stated that for frontend developers, there is a place where they can explicitly see the required mandatory variables that is the graphQL section of the admin repository. In fact, I am surprised that if you are an experienced graphQL developer, then you shouldn’t have required my screenshot in order to figure out that the first and skip were required. 

I am talking about the developers working in the API,  when I am saying, they should understand the resolvers. Because the developer who do not understand the working of a resolver should not be contributing to the graphQL section of the API. That is why good first issues are meant in an organisation to get hold of the repository. In fact, I am the one who is saying that they can refer the documentation. Because the comments are also part of documentation and I’m not telling them to understand the resolver. I’m simply telling them to go and read the comments over the resolvers.  So when you say why documentations are required, you are simply contradicting yourself because I am the one emphasising from the beginning that in the comments over the resolver, it is clearly stated that the first argument is required.  

In fact, I am not the one debating I am saying from the start if you feel that it can help new contributors then you can create a good first issue. Because it is a one line implementation. You are the one extending it. If you read my comments above in every comment at the end, I have said, if you feel that new contributor can benefit from it. Then you can go and create the issue I even said that we should end the conversation. You are the one who is extending it. There is no debate. In fact we have much major problems in the API which mostly involves faulty implementations due to inexperienced developers being allowed to work in parts, they do not understand and at the end other contributor face problems. I know this can happen in an open source environment and that is why we should focus on major issues. 

There is nothing with what I feel. I can clearly see that the issue has been solved and that the code I have written solves the issue completely. It Is not even a debate. I hope this conversation ends here because rather than arguing with me you could have simply created a good first issue in the first place when I suggested so. but rather than doing so you kept on extending the conversation. Thank you.
