### ISSUE TITLE
Only allow the creation of new organizations from Talawa Admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#236]
Any Talawa mobile app user has the ability to create multiple organizations. [This needs to be centralized as part of of the functionality of the new talawa-admin repo.](https://github.com/PalisadoesFoundation/talawa-admin/issues/19)

For this to be successful, the API must:

1. Only allow the creation of new organizations by Talawa-Admin clients only
1. These Talawa-Admin clients must be preapproved somehow, preferably in a configuration file normally inaccessible over a network connection.

Related Issues:

1. [Issue 236 - Talawa API](https://github.com/PalisadoesFoundation/talawa-api/issues/236)
2. [Issue 19 - Talawa Admin](https://github.com/PalisadoesFoundation/talawa-admin/issues/19)
3. [Issue 710 - Talawa](https://github.com/PalisadoesFoundation/talawa/issues/710)

**Comment by XshubhamX** [comment]
@palisadoes Sir I have idea, what if all the admin clients can get a key to create an organization from talawa admin portal. All the keys should be unique for every client . Now in order to create an organization at talawa they have to enter the specific key . Now if the key is found reliable by talawa Api then the organization building process can be taken forward ,other wise the api should throw an error Invalid key. Does it looks good sir.

**Comment by palisadoes** [comment]
@XshubhamX When you say *admin clients* do you mean the mobile app clients? 

Remember, we need to remove the app being able to create organizations. The app needs to focus on being a good organization membership communication platform

**Comment by XshubhamX** [comment]
@palisadoes Sir so the objectives are as follows:

1: User (who wants to create an organization) should log in into the the talawa-admin portal. 

2: In talawa admin we have to add a functionality with the help of which a user can create org, basically we need to make request to talawa-Api (create organization mutation)

Sir i want to suggest 1 more thing. Sir currently there is not much code in talawa admin and as we know that node works great with react, so sir if its possible can i change the whole code into a react SPA , Because sir talawa Admin will eventually be a small application and React Spa's will provide good functionality and reliability .Further decision is yours sir but truly react will inhance UX and UI.

**Comment by palisadoes** [comment]
@heyjordn, @XshubhamX would like to convert Talawa-Admin to `react.js`. As we don't have much code there, maybe now is the time to do so. What was the rationale for going with `vue.js` and `typescript`?

We haven't had many issue created for Talawa-Admin and the language choice may be a factor.

**Comment by palisadoes** [comment]
@DangaRanga may have some insights here too.

**Comment by XshubhamX** [comment]
@palisadoes Sir I will wait for the decision until then i'm working on #235 .

**Comment by XshubhamX** [comment]
@palisadoes sir please merge my #226 pr because this is from my develop branch and I want to make further changes into this branch in a new pr .And also this pr is fixing a major bug during file upload.

**Comment by palisadoes** [comment]
@XshubhamX  

1. Do you think we'll get more participation with PRs for the `talawa-admin` repo if we migrate to react? 
2. Do you know of any others in the slack channel who would be willing to assist you in the task?

**Comment by XshubhamX** [comment]
@palisadoes sir there are many mean stack developers in slack channel who can contribute to the project.

**Comment by palisadoes** [comment]
If you think you can do the migration, then go ahead. We need progress, and we don't have any now.

Who would you think we could work with?

**Comment by DangaRanga** [comment]
I apologize for the late reply to this thread,

Personally, I believe migrating to `react.js` would also increase the contributions to Talawa-Admin, due to it being the more popular of the two frameworks and having a slightly lower learning curve, thus more people would be familiar with it.

Otherwise from a functional standpoint there aren't really any limitations between using React.js or Vue.js for Talawa-Admin(or at least none that I am currently aware of), however Typescript had been chosen to minimize the amount of issues that usually arise with using javascript from not having static typing enforced.

So in my opinion, switching to React.js and Typescript would also be a viable option.

**Comment by XshubhamX** [comment]
@DangaRanga sir i think lets delete every thing in repository leaving pr template and issue template ans lets start from scratch by creating app using create-react-app.What do you think sir.

**Comment by palisadoes** [comment]
@XshubhamX  please go ahead. Make sure the installation and README.md documentation are appropriately updated.

**Comment by XshubhamX** [comment]
@palisadoes ok sir

**Comment by yasharth291** [comment]
Hello sir

**Comment by yasharth291** [comment]
This could be closed now @palisadoes  it is done
