### ISSUE TITLE
Feature request for having images in events

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#329]
**Is your feature request related to a problem? Please describe.**
While adding/editing the event, users should also be able to add/update pictures related to it. Attaching a picture to an event is optional, the event may or may not have a picture.

**Describe the solution you'd like**
Schema Updates for the event, Mutation Updates for adding event and updating it and Query Updates.
For Images, we will dump data on the cloud and store generated links in the event model.

**Additional context**
This is a request by @utkarshshendge

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by VaibhavSethia07** [comment]
Please assign me this issue. I am going to store the event's images in the AWS S3 bucket via the upload folder on the server. The image URL will be stored as a string in the Event's Mongoose model. This is done so as to get extra time to check if the user is authenticated, event exists, etc. Then we can fetch the images using the URL stored in MongoDB.

**Comment by Sagar2366** [comment]
@VaibhavSethia07 thank you for your interest.
Assigning this issue to you.

**Comment by palisadoes** [comment]
@VaibhavSethia07 There is more to this than creating an AWS link.

- How are you going to reliably handle de-duplication of the data to reduce the storage requirements?
- How will Talawa-API contributors be able to test Talawa-API without having an AWS link? Not everyone will have access to AWS or other cloud providers.
- How will your design facilitate the addition of other cloud providers in future?
- How will the configuration steps for Talawa-API change?
- What testing regime will to create to make this work? We are trying hard to increase our test code coverage levels. The code you add will need to be 100% covered by tests.

These are not difficult challenges, but will need to be a part of your solution. Good luck!

**Comment by VaibhavSethia07** [comment]
Yes @palisadoes, you rightly pointed out the challenges. My approach to these problems are as follow:

- How are you going to reliably handle the de-duplication of the data to reduce the storage requirements?
All the images will be stored in the S3 bucket by their unique key and will have a hash value. This hash value can be generated from the image's path. If an image with the hash value is already present in the S3 bucket, we will delete the previously uploaded image and upload the current image.

- How will Talawa-API contributors be able to test Talawa-API without having an AWS link? Not everyone will have access to AWS or other cloud providers.
In the AWS account, I can create a policy that allows certain operations(CRUD) to the bucket. I can then create a user which is our application and assign this policy to the user. So our application Talawa-API can access the bucket.  

- How will your design facilitate the addition of other cloud providers in the future?
I don't know how to address this problem because AWS uses the access key and secret key for authorization. Other cloud providers have different configurations, so it will be difficult to add other cloud providers.

- How will the configuration steps for Talawa-API change?
The only change is in the .env file where we have to provide the AWS bucket name, region, access key, and secret access key. However, the Secret Key cannot be shared publicly. So I have to think about solving this issue.

- What testing regime will you create to make this work? We are trying hard to increase our test code coverage levels. The code you add will need to be 100% covered by tests.
We can store some test images in the image folder of the Talawa-API and use them in the tests created for the mutations and queries related to Events.

I am new to open-source development and trying to make significant contributions. I am open to suggestions.

**Comment by palisadoes** [comment]
Thanks for the note. The answers are clear. You need to dig a little deeper.

- Not everyone who is a contributor will have the funds, credit card, or school free access to work with AWS. How will they be able to continue testing the API without AWS? In other words, can there be an option to store the data on local storage for purposes of development and/or organizations who don't have AWS access either? I'm more concerned about the former, than the latter. How would you propose to do this?
- How would you prevent duplication of data if an object (file) is shared or forwarded to other people on the platform? In other words, how will you handle someone deleting a chat that was forwarded to them without deleting it for everyone? 
- On which filepath would the de-duplication be based? If it's that of the source directory of the upload, there is the risk of two people uploading different files with the same name. For example ~/Downloads/IMG-0051.JPG`, which is a generic phone photo file name. User A could overwrite the content of user B. The hash will need to inspect the content of the file. 
- Consider ways to handle files that are copied with different names, but are uploaded without duplicating the content in storage.

**Comment by VaibhavSethia07** [comment]
I have to learn more to solve the above-mentioned issues. Please unassign me right now.

**Comment by palisadoes** [comment]
I'm sure that with a little research answers to these challenges can be found. There should be lots of online articles on the strategies for handling content in social media and chat apps.
