### ISSUE TITLE
[Bug] Countline.py Changes as per new modifications

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#469]
**Describe the bug**
The repository has currently gone through the folder restricting. As per the new structure changes, countline python code needs to be optimised to check and monitor the number of lines as per the new directory.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open the Countline.py file in the workflow folder
2.  The folder contains the lib directory checking, which is no longer required
3. Optimise the countline for the src folder and subfolder
4. Optimise the countline for the test folder

**Expected behaviour**
Not all subfolder requires countline checking like Schema, config etc. Remove them and add required API based subfolders and files only. Also, the amount of lines in the test folder needs to be optimised as well.

**Additional details**
Please feel free to comment for any doubts

**Comment by palisadoes** [comment]
The identical script is used in all three `talawa` repos. It was recently updated.

- You can already exclude entire directories by using the `--exclude_directories` flag. You can add `test/` and `lib/config` to that list.
- We included `src` to the check list because `talawa-api` was still using it. We can update this when the code is completely refactored.
- https://github.com/PalisadoesFoundation/talawa-api/issues/470 Requests the assignee to rename `src` to `lib`, so this issue should therefore be updated to include `lib` but remove `src`
