### ISSUE TITLE
Resolvers: Create tests for addUserToGroupChat.js

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#534]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/group_chat_mutations/addUserToGroupChat.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/group_chat_mutations/addUserToGroupChat.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/group_chat_mutations/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by saga2405** [comment]
can you assign this to me. I've made PRs for the two issues that were assigned to me. Now I can work on a new issue

**Comment by palisadoes** [comment]
We need to get the code coverage up to 100% for this file.

**Comment by saga2405** [comment]
The current status of code coverage is as shown
![Screenshot (1651)](https://user-images.githubusercontent.com/66516087/164717520-22609c76-677d-4258-a2cd-0ad9f8b3f325.png)
The fact that it is 75 because of the two blocks of code in the main function which executes in case of an error, as shown
![Screenshot (1650)](https://user-images.githubusercontent.com/66516087/164717715-5f9b4f47-e1d0-43bd-b6b8-e0aa76f800b6.png)
![Screenshot (1653)](https://user-images.githubusercontent.com/66516087/164717732-47b28a27-5c47-445d-9ef8-00767f3dd764.png)
So there is an environment check in both of the blocks at lines 12 and 32, to check if the code is running in the production server or not, in case it is running in production then the translate function gets triggered
so as I am not running the code in the production environment so that block of code is not used completely and that's the reason the coverage is 75

**Comment by palisadoes** [comment]
Is there an alternative approach to prevent this?

**Comment by saga2405** [comment]
Yes sir,  removing the environment check from the function and removing the ternary operator can fix this and can take the code coverage to 100.
The environment check is just an efficient and fast way of testing code in local enviroment
