### ISSUE TITLE
ES Lint Auto Fix

### ISSUE THREAD

**Issue by sandeep-v1404** [PalisadoesFoundation/talawa-api#691]
**Is your feature request related to a problem? Please describe.**
ESLint throws the errors and formats the code but the changes are not being reflected in the commit.

**Describe the solution you'd like**
When a commit is made in a PR, even if `npm run lint` is not done by the user who makes the commit and if there are no errors thrown by the ESLint, the code format should take place automatically.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
This [action](https://github.com/marketplace/actions/lint-action#javascript-example-eslint-and-prettier) helps us fix this issue.

**Comment by SiddheshKukade** [comment]
@sandeep-v1404 I think linting the code during the development phase in a pull request can be a subject of choice because a lot of things are being tried and tested during the dev phase. when the changes are finalized or when they reach a particular milestone the code can then be linted properly by the developer and he can take some decisions. So I think doing `npm run lint ` automatically is not a good idea. 
but the second thing which you told me about auto-formatting I think this will be very beneficial for someone who's not using VSCode or the prettier plugin

**Comment by palisadoes** [comment]
@SiddheshKukade It is harder to review code when it's not linted as new formatting will be highlighted in the diffs.

**Comment by SiddheshKukade** [comment]
Hello @sandeep-v1404 It's been over 6 months since this issue is opened and there is also not any PR associated with this. I will close this issue for now.
