### ISSUE TITLE
Resolvers: Create Test for resolvers/MembershipRequest index.ts

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#807]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/lib/resolvers/MembershipRequest/index.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/MembershipRequest/index.sepc.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/develop/src/lib/resolvers/MembershipRequest/index.ts). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by beingnoble03** [comment]
@SiddheshKukade the code coverage is already 100% for `src/lib/resolvers/MembershipRequest/organization.ts` and `src/lib/resolvers/MembershipRequest/user.ts`. If these are the files referred here, can we close this issue?

**Comment by palisadoes** [comment]
@beingnoble03 Thanks for highlighting this. We'll review later.  Please continue your approach on other tests.

**Comment by beingnoble03** [comment]
Sure @palisadoes. There are more issues having 100% code coverage. We'll need to review them too. Thanks!

**Comment by beingnoble03** [comment]
Sorry, I think the path `lib/resolvers/MembershipRequest/index.ts` is referred here.

**Comment by palisadoes** [comment]
@beingnoble03 I think you are correct. We trying to converted the code base to typescript and issues related to testing the  old javascript still exist. Please proceed.

Can you also address these too so that we can cover all the tests related to Membership requests? I'll work with @SiddheshKukade to fix the outstanding issues.

```
resolvers/MembershipRequest/index.ts
resolvers/MembershipRequest/organization.ts
resolvers/MembershipRequest/user.ts
```

**Comment by beingnoble03** [comment]
Sure @palisadoes.

**Comment by beingnoble03** [comment]
https://github.com/PalisadoesFoundation/talawa-api/pull/823#issuecomment-1366568984 needs to be addressed before I proceed with this issue because `resolvers/MembershipRequest/organization.ts` and `resolvers/MembershipRequest/user.ts` are already 100% covered, and we need to check if we want to create tests for `resolvers/MembershipRequest/index.ts` or not. Thanks!

**Comment by beingnoble03** [comment]
@SiddheshKukade can you please assign me this issue?

**Comment by SiddheshKukade** [comment]
The valid file path and coverage links are updated now.
