### ISSUE TITLE
Not able to add tags in Organization

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-api#853]
**Describe the bug**
Cannot add tags in the organization, while creating it.
Getting error

![image](https://user-images.githubusercontent.com/67755128/211367818-032c26bc-2219-4774-a0a5-f2b1da74fedc.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create organization through graphql interface

![image](https://user-images.githubusercontent.com/67755128/211367706-fdbff157-a4a8-40b5-b288-d5476cec6175.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/211368020-2eecf90e-13ff-4913-bc3a-fe2d2d2cdafe.png)

**Additional details**
Due to this issue, the organization cannot be created on frontend

https://github.com/PalisadoesFoundation/talawa-admin/issues/370

https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1672987548733609?thread_ts=1672903169.859759&cid=C01RPC00K0D

**Comment by VenomFate-619** [comment]
I like to resolve this.

**Comment by VenomFate-619** [comment]
what I think is that we need to add a `tag` in `OrganizationInput` typeDef

**Comment by palisadoes** [comment]
What is the use case for adding tags when creating an organization?

**Comment by VenomFate-619** [comment]
Tags will have following benefits
- Formation of category for organization
- Searching based on tag 
- tag will act as keywords for searching
- Tags can be added and removed as needed, giving users the ability to customize their organization and categorization of information within the application.
- Tags can provide additional context 
-  Tags can be used to generate reports and perform analytics on data and help to identify trend and pattern

**Comment by rv602** [comment]
@palisadoes ,  I was working on solving <a href='https://github.com/PalisadoesFoundation/talawa-admin/issues/276'>this issue</a> in the talawa-admin repository, and the reason all test cases don't pass is because of the errors caused due to the tags property.

After modifying the code and removing the tags property, all test cases ran successfully.

Also, there is another issue in the talawa-admin repository itself - <a href='https://github.com/PalisadoesFoundation/talawa-admin/issues/370'>link</a> that is caused due to the tags property error.

I made a <a href='https://github.com/PalisadoesFoundation/talawa-admin/issues/370#issuecomment-1374837810'>comment</a> there as well, stating that by removing the tags property, we can successfully create a new organisation.

Hence I feel that removing the tags property would solve many issues.

**Comment by VenomFate-619** [comment]
@rv602 according to this [discussion](https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1672987548733609?thread_ts=1672903169.859759&cid=C01RPC00K0D)  tags functionality should be added at the backend instead of removing it from frontend

**Comment by nishant3721** [comment]
@palisadoes can I work on it?

**Comment by palisadoes** [comment]
@VenomFate-619 Are you still interested in working on this? If not I'll assign to @nishant3721 tomorrow.

**Comment by VenomFate-619** [comment]
Yes  , i am working on it.It is completed, just setting up the things for the PR
